#!/usr/bin/env sh

set -e

main() {
    git clone 'https://github.com/TruncatedDinosour/dm'
    cd dm || exit 1

    if [ "$1" != "full" ]; then
        make dm-update
    else
        make deps
        make dm-full-setup
    fi

    cd ..
    rm -rf dm
    dm clean
}

main "$@"

